title:              "마케티파이"
tagline:            "Marketify : 송하몽의 마케팅 블로그"
email:              "ssongji15@naver.com"
description:        "자동차 마케터가 보여주는 업계 및 디지털 마케팅 이야기"
author:             "송하몽"
baseurl:            ""
url:                "https://mmktify.com"
locale:             "ko_KR"
thumbnail:          "/img/main_thumbnail.jpg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: support.song
facebook_username:  facebook_username
linkedin_username:  in/jiwonsong921101

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate


# 블로그 disqus shortname
disqus:
  shortname: http-mmktify-com
